language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
env:
  - DJANGO=django==1.3
  - DJANGO=django==1.4
  - DJANGO=django==1.5
  - DJANGO=django==1.6
  - DJANGO=https://www.djangoproject.com/download/1.7b1/tarball/
matrix:
  exclude:
    # Django < 1.5 not supported on python 3
    - python: "3.2"
      env: DJANGO=django==1.3
    - python: "3.2"
      env: DJANGO=django==1.4
    # Django >= 1.5 strongly recommends python 2.7 or later (so skip 2.6)
    - python: "2.6"
      env: DJANGO=django==1.5
    - python: "2.6"
      env: DJANGO=django==1.6
    - python: "2.6"
      env: DJANGO=https://www.djangoproject.com/download/1.7b4/tarball/
install:
  - pip install -q $DJANGO
  - pip install .
script: python -Wall setup.py test
